package com.example.daily.ui.theme

import androidx.compose.ui.graphics.Color

// --- Светлая Тема ---
val PrimaryLight = Color(0xFF00639B)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFCFE5FF)
val OnPrimaryContainerLight = Color(0xFF001D33)
val SecondaryLight = Color(0xFF51606F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD4E4F6)
val OnSecondaryContainerLight = Color(0xFF0D1D2A)
val TertiaryLight = Color(0xFF67587B)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFEEDCFF)
val OnTertiaryContainerLight = Color(0xFF221534)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFCFCFF)
val OnBackgroundLight = Color(0xFF1A1C1E)
val SurfaceLight = Color(0xFFFCFCFF)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFDFE2EB) // Для контейнеров/карточек
val OnSurfaceVariantLight = Color(0xFF42474E)
val OutlineLight = Color(0xFF73777F)
val ScrimLight = Color(0xFF000000)

// --- Тёмная Тема ---
val PrimaryDark = Color(0xFF99CBFF)
val OnPrimaryDark = Color(0xFF003353)
val PrimaryContainerDark = Color(0xFF004B76)
val OnPrimaryContainerDark = Color(0xFFCFE5FF)
val SecondaryDark = Color(0xFFB8C8D9)
val OnSecondaryDark = Color(0xFF233240)
val SecondaryContainerDark = Color(0xFF394857)
val OnSecondaryContainerDark = Color(0xFFD4E4F6)
val TertiaryDark = Color(0xFFD2BFE8)
val OnTertiaryDark = Color(0xFF382A4A)
val TertiaryContainerDark = Color(0xFF4F4162)
val OnTertiaryContainerDark = Color(0xFFEEDCFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF121212)
val OnBackgroundDark = Color(0xFFE2E2E5)
val SurfaceDark = Color(0xFF121212)
val OnSurfaceDark = Color(0xFFE2E2E5)
val SurfaceVariantDark =  Color(0xFF282828)
val OnSurfaceVariantDark = Color(0xFFC3C6CF)
val OutlineDark = Color(0xFF8D9199)
val ScrimDark = Color(0xFF000000)
